Added dismiss button to alerts
ideas-edu/logictools pull request #136
Opened 2021-05-21 12:05 UTC by BenEdV

Resolves #128 
Test [here](https://www.bendevries.com/logictools/128_dismiss_alert)

2021-05-27 12:49 UTC, josjelodder requested changes
als ik vergeet de toegepaste regel mee te geven, verhuist het commentaar eerst een plek naar boven (dat staat kennelijk lager dan ander commentaar) en pas als dan nogmaals het kruisje aanklik sluit het venster

2021-05-31 10:05 UTC, BenEdV commented
> als ik vergeet de toegepaste regel mee te geven, verhuist het commentaar eerst een plek naar boven (dat staat kennelijk lager dan ander commentaar) en pas als dan nogmaals het kruisje aanklik sluit het venster

Zou je een screenshot kunnen geven? Is dit met de LogEx tools? Bij mij werkt zoals het eerder was maar dan met een kruisje om de alert te sluiten.

2021-05-31 12:15 UTC, josjelodder commented
het gaat op je testpagina niet goed bij de equivalenties:
![image](https://user-images.githubusercontent.com/16118925/120191349-1c9e3280-c21a-11eb-99fe-70f9dd4e7bd3.png)
na sluiten via het kruisje krijg je
![image](https://user-images.githubusercontent.com/16118925/120191474-40fa0f00-c21a-11eb-9991-62c2275b9ada.png)

idem bij dnf
![image](https://user-images.githubusercontent.com/16118925/120191703-8ddde580-c21a-11eb-9feb-f726e3cf554a.png)
na sluiten
![image](https://user-images.githubusercontent.com/16118925/120191752-9c2c0180-c21a-11eb-908e-5a8bcb69e35e.png)

2021-06-03 15:14 UTC, josjelodder approved these changes
werk nu prima

2021-06-04 08:54 UTC, merged