Changed phi -> sigma in LogAx goal
ideas-edu/logictools pull request #211
Opened 2021-06-24 14:28 UTC by BenEdV

Resolves #209 
Test [here](https://www.bendevries.com/logictools/209_update_goal_text)

2021-06-25 12:59 UTC, josjelodder requested changes
de komma op het toetsenbord is ok, maar nu moet de phi voor de |- nog een Sigma zijn

2021-06-25 13:29 UTC, BenEdV commented
Misschien is er een probleem met het cachen. Ik zie dit
<img width="532" alt="Screen Shot 2021-06-25 at 3 29 03 PM" src="https://user-images.githubusercontent.com/10991906/123432006-31c47200-d5ca-11eb-9f92-2cd70b3935a0.png">

2021-06-25 13:51 UTC, josjelodder commented
Vreemd., ik heb zowel in chrome als firefox nu een privevenster gestart, maar heb nog steeds een phi ipv psi

Van: Ben de Vries ***@***.***>
Verzonden: vrijdag 25 juni 2021 15:30
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] Changed phi -> sigma in LogAx goal (#211)


Misschien is er een probleem met het cachen. Ik zie dit
[Screen Shot 2021-06-25 at 3 29 03 PM]<https://user-images.githubusercontent.com/10991906/123432006-31c47200-d5ca-11eb-9f92-2cd70b3935a0.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/ideas-edu/logictools/pull/211#issuecomment-868501254>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AD27JDM7VP6CXLLM2IVDMJTTUSAGHANCNFSM47IAKIRQ>.

2021-06-25 13:55 UTC, BenEdV commented
Ik heb net de headers op mijn server aangepast zodat ze `no-store` meegeven. Hopelijk zorgt dat voor minder van deze problemen.

2021-06-28 09:28 UTC, josjelodder commented
ik heb het nu ook nog op mijn vaste computer getest, en ook daar krijg ik de sigma niet te zien, terwijl ik niet weet of ik daar ooit de axiomatic heb uitgeprobeerd. Ook weggooien van cache leek niet te helpen

2021-08-17 09:41 UTC, josjelodder approved these changes
Ik zal hem maar op approve zetten, maar bij mij staat hier toch nog altijd een phi ipv een sigma

2021-08-17 10:15 UTC, merged