163 update logax styling
ideas-edu/logictools pull request #217
Opened 2021-06-28 08:02 UTC by BenEdV

Resolves #163 and resolves #183 
Test [here](https://www.bendevries.com/logictools/163_update_logax_styling)

2021-06-28 09:46 UTC, josjelodder reviewed
de styling tot zover lijkt ok, er staat dat deze commit ook betrekking heeft op de video, maar de helppagina is in deze versie kapot. En kan de tekst in een foutmelding weer zwart ipv rood?

2021-07-15 08:19 UTC, josjelodder requested changes
het aanmaken van een opgave blijft in deze versie hangen, dus ik kan het niet testen

2021-07-15 15:12 UTC, BenEdV commented
> het aanmaken van een opgave blijft in deze versie hangen, dus ik kan het niet testen

Opgelost

2021-07-16 12:50 UTC, josjelodder approved these changes
dit ziet er mooi uit zo

2021-07-16 13:06 UTC, merged