Added collapsing of cases
ideas-edu/logictools pull request #357
Opened 2022-02-06 12:27 UTC by BenEdV

Resolves #354 
Test [here](https://www.bendevries.com/logictools/354_collapse)

2022-02-08 10:40 UTC, josjelodder requested changes
Wat nog niet goed gaat  is, wanneer ik bijv via een hint alle inductieve gevallen klaar heb staan,  en degene die ik niet gebruik ingeklapt heb, en na afronden van het actieve geval via een hint een volgend geval wil uitwerken. Er lijkt dan niets te gebeuren, en pas als ik het geval uitklap zie je dat hier ondertussen wel wat wordt gedaan.

2022-02-11 10:20 UTC, BenEdV commented
> Wat nog niet goed gaat is, wanneer ik bijv via een hint alle inductieve gevallen klaar heb staan, en degene die ik niet gebruik ingeklapt heb, en na afronden van het actieve geval via een hint een volgend geval wil uitwerken. Er lijkt dan niets te gebeuren, en pas als ik het geval uitklap zie je dat hier ondertussen wel wat wordt gedaan.

Mogelijk is dit beter opgelost op de achterkant. Als er een hint komt voor een geval dat al begonnen is maar niet actief dan stuurt de backend dat er geen actieve geval is. Ik denk dat als er hint wordt gebruikt dat het geval ook actief moet worden. In dat geval hoeft de voorkant niet te worden aangepast.

2022-02-18 09:53 UTC, josjelodder commented
en hier nog een betere screendump, zodat je kunt zien dat er rechts wel een stap is gezet
![image](https://user-images.githubusercontent.com/16118925/154659555-5e2b2580-3e60-4f3b-948b-24f02430ed8a.png)

2022-02-18 14:07 UTC, josjelodder approved these changes
lijkt nu goed te werken

2022-02-18 15:01 UTC, merged