32 syntax
ideas-edu/logictools pull request #50
Opened 2021-04-07 15:02 UTC by BenEdV

Resolves #32 and  #41
Test [here](https://www.bendevries.com/logictools/32_syntax/)

2021-04-09 09:08 UTC, josjelodder requested changes
voor he ontbreken van haakjes gaat dit goed, bij dubbelzinnig bereik zou ik een andere tekst willen, maar deze in de bijlage is nog niet goed (je krijgt waarschijnlijk een Did you forget an operator bericht terug van onze kant
[syntax.docx](https://github.com/ideas-edu/logictools/files/6284537/syntax.docx)

2021-04-09 13:04 UTC, BenEdV commented
Ik heb deze een foutmelding gegeven en het geval (q∨¬r)∧(q¬q) toegevoegd aan de lijst van tests op de syntax validator.

2021-04-12 08:45 UTC, BenEdV commented
Ik zie dat de backend p ↔ q ↔ r en p → q → r als dubbelzinnig beschouwen. Klopt het dat impliciete associativiteit alleen voor de en- en of-operaties geldt?

2021-04-12 08:57 UTC, josjelodder commented
Ja, dat klopt, Josje

Van: Ben de Vries ***@***.***>
Verzonden: maandag 12 april 2021 10:46
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] Add syntax validation of user input (#50)


Ik zie dat de backend p ↔ q ↔ r en p → q → r als dubbelzinnig beschouwen. Klopt het dat impliciete associativiteit alleen voor de en- en of-operaties geldt?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/ideas-edu/logictools/pull/50#issuecomment-817616196>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AD27JDLRM5W6MICYFL3IH23TIKXMFANCNFSM42Q65LSA>.

2021-04-13 07:45 UTC, merged